# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    filter_sets:
        my_min_up_scale_filter:
            filters:
                upscale:
                    min: [3960, 2560]

        my_by_up_scale_filter:
            filters:
                upscale:
                    by: 0.7

        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow-upscale: true
        
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow-upscale: true